name: 'Publish Release'
description: 'Composite action to publish a release'
inputs:
  configuration:
    description: 'The build configuration to use'
    required: true
    default: 'Release'
  config_name:
    description: 'The configuration file name for release drafter'
    required: true
    default: 'release-drafter.yml'
runs:
  using: 'composite'
  steps:
    - name: Publish Project
      run: dotnet publish src/CodeCount/CodeCount.csproj --configuration ${{ inputs.configuration }} --output ./publish
      shell: bash

    - name: Draft Release
      id: draft_release
      uses: release-drafter/release-drafter@v5
      with:
        config-name: ${{ inputs.config_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.draft_release.outputs.upload_url }}
        asset_path: ./publish/*
        asset_name: CodeCount.zip
        asset_content_type: application/zip
