name: 'Publish Release'
description: 'Composite action to publish a release'
inputs:
  configuration:
    description: 'The build configuration to use'
    required: true
    default: 'Release'
  config_name:
    description: 'The configuration file name for release drafter'
    required: true
    default: 'release-drafter.yml'
  github_token:
    description: 'GitHub token for authentication'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Publish Project
      run: dotnet publish src/CodeCount/CodeCount.csproj --configuration ${{ inputs.configuration }} --output ./publish --runtime win-x64 --self-contained --p:DebugType=None
      shell: bash

    - name: Zip Artifacts
      run: |
        cd publish
        zip -r CodeCount.zip .
      shell: bash

    - name: Draft Release
      id: draft_release
      uses: release-drafter/release-drafter@v5
      with:
        config-name: ${{ inputs.config_name }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      if: success()
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        upload_url: ${{ steps.draft_release.outputs.upload_url }}
        asset_path: publish/CodeCount.zip
        asset_name: CodeCount.zip
        asset_content_type: application/zip
