name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/OWNER/REPO/compare/$PREVIOUS_TAG...$NEW_TAG
