name: Create Release

on:
  pull_request:
    types: [closed]

permissions:
  checks: write
  contents: write
  pull-requests: write  # This is required even though there is no PR as it causes step errors.

jobs:
  draft-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.draft_release.outputs.upload_url }}

    steps:
    - name: Draft Release
      id: draft_release
      uses: release-drafter/release-drafter@v5
      with:
        config-name: 'release-drafter.yml'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-release-windows:
    needs: draft-release
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Restore and Build
      uses: ./.github/actions/restore-build
      with:
        dotnet-version: '8.0.x'
        configuration: 'Release'

    - name: Run Unit Tests
      run: dotnet test src --configuration Release --no-build --verbosity normal
      shell: bash

    - name: Publish Project
      run: dotnet publish src/CodeCount/CodeCount.csproj --configuration Release --output ./publish --runtime win-x64 --self-contained --p:DebugType=None
      shell: bash

    - name: Zip Artifacts
      run: |
        Compress-Archive -Path ./publish/* -DestinationPath ./publish/CodeCount-win-x64.zip
      shell: pwsh

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.draft-release.outputs.upload_url }}
        asset_path: publish/CodeCount-win-x64.zip
        asset_name: CodeCount-win-x64.zip
        asset_content_type: application/zip
