name: Create Release

on:
  pull_request:
    types: [closed]

jobs:
  create_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Restore and Build
      uses: ./.github/actions/restore-build
      with:
        dotnet-version: '8.0.x'
        configuration: 'Release'

    - name: Run Tests
      uses: ./.github/actions/run-tests
      with:
        configuration: 'Release'

    - name: Publish Release
      uses: ./.github/actions/publish-release
      with:
        configuration: 'Release'
        tag_name: 'v1.0.0'
        release_name: 'Release v1.0.0'
        release_body: 'Release notes for version 1.0.0'
