name: PR Labels

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  pull-requests: write

jobs:
  add-labels:
    name: Add Labels
    runs-on: ubuntu-latest
    steps:
      - name: Add Conventional Release Labels
        uses: bcoe/conventional-release-labels@v1
