name: Run Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src

      - name: Build solution
        run: dotnet build src --no-restore

      - name: Run tests
        run: dotnet test src --no-build --verbosity normal --logger trx --collect:"XPlat Code Coverage" --results-directory ./test-results

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()        
        with:
          files: |
            test-results/**/*.trx
          check_run: false

      - name: Publish test report
        uses: dorny/test-reporter@v1.9.1
        if: always()
        with:
          name: Test Results
          path: test-results/**/*.trx
          reporter: dotnet-trx

      - name: Generate code coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: test-results/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add test coverage PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
